"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Dashboard={players:number;clubs:number;countries:number;competitions:number;articles:number;collections:number;shortlists:number;users:number;audit:Array<{id:string;action:string;entityName:string;entityId:string;details:string;createdAt:string}>};
type AdminPlayer={id:string;slug:string;firstName:string;lastName:string;primaryPosition:string;currentAbility:number;potentialAbility:number;marketValue:number;country:string;club:string|null};
const API=(process.env.NEXT_PUBLIC_API_URL??"http://localhost:8080/api").replace(/\/$/,"");

export default function AdminPage(){
 const [key,setKey]=useState(""); const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [players,setPlayers]=useState<AdminPlayer[]>([]); const [message,setMessage]=useState(""); const [query,setQuery]=useState("");
 const headers=useMemo(()=>({"X-Admin-Key":key}),[key]);
 async function load(){setMessage("");const [d,p]=await Promise.all([fetch(`${API}/admin/dashboard`,{headers}),fetch(`${API}/admin/players?q=${encodeURIComponent(query)}`,{headers})]);if(!d.ok||!p.ok){setMessage("Admin anahtarı veya API bağlantısı geçersiz.");return;}setDashboard(await d.json());setPlayers((await p.json()).items)}
 useEffect(()=>{const saved=localStorage.getItem("fm26_admin_key");if(saved)setKey(saved)},[]);
 async function connect(e:FormEvent){e.preventDefault();localStorage.setItem("fm26_admin_key",key);await load()}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const input=e.currentTarget.elements.namedItem("file") as HTMLInputElement;if(!input.files?.[0])return;const body=new FormData();body.append("file",input.files[0]);setMessage("İçe aktarılıyor...");const r=await fetch(`${API}/admin/players/import-csv`,{method:"POST",headers,body});const x=await r.json();setMessage(r.ok?`${x.imported} oyuncu eklendi, ${x.skipped} satır atlandı, ${x.errors.length} hata.`:(x.error??"Import başarısız."));if(r.ok)await load()}
 async function remove(id:string){if(!confirm("Oyuncu silinsin mi?"))return;const r=await fetch(`${API}/admin/players/${id}`,{method:"DELETE",headers});setMessage(r.ok?"Oyuncu silindi.":"Silme başarısız.");if(r.ok)await load()}
 return <main className="page container"><header className="page-head"><span className="eyebrow">OPERATIONS</span><h1>Admin Center</h1><p>Veri yönetimi, CSV aktarımı ve sistem denetimi.</p></header>
 <form className="panel admin-connect" onSubmit={connect}><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Render ADMIN_KEY"/><button className="btn btn-primary">Bağlan</button></form>
 {message&&<p className="panel admin-message">{message}</p>}
 {dashboard&&<><section className="admin-stats">{Object.entries(dashboard).filter(([k])=>k!=="audit").map(([k,v])=><article className="panel stat" key={k}><span>{k.toUpperCase()}</span><strong>{String(v)}</strong></article>)}</section>
 <section className="panel admin-section"><div><span className="eyebrow">DATA PIPELINE</span><h2>Oyuncu CSV aktarımı</h2><p>Şablon: <code>supabase/player-import-template.csv</code></p></div><form onSubmit={upload} className="admin-upload"><input name="file" type="file" accept=".csv,text/csv"/><button className="btn btn-primary">CSV yükle</button></form></section>
 <section className="admin-section"><div className="section-head"><div><span className="eyebrow">PLAYERS</span><h2>Oyuncu yönetimi</h2></div><form onSubmit={e=>{e.preventDefault();void load()}} className="admin-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Oyuncu ara"/><button className="btn">Ara</button></form></div><div className="panel admin-table-wrap"><table className="admin-table"><thead><tr><th>Oyuncu</th><th>Konum</th><th>CA / PA</th><th>Değer</th><th></th></tr></thead><tbody>{players.map(p=><tr key={p.id}><td><strong>{p.firstName} {p.lastName}</strong><small>{p.slug}</small></td><td>{p.primaryPosition}<small>{p.club??"Serbest"} · {p.country}</small></td><td>{p.currentAbility} / {p.potentialAbility}</td><td>{new Intl.NumberFormat("tr-TR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(p.marketValue)}</td><td><button className="btn danger" onClick={()=>void remove(p.id)}>Sil</button></td></tr>)}</tbody></table></div></section>
 <section className="admin-section"><span className="eyebrow">AUDIT LOG</span><h2>Son işlemler</h2><div className="panel audit-list">{dashboard.audit.map(x=><div key={x.id}><strong>{x.action} · {x.entityName}</strong><span>{x.details||x.entityId}</span><time>{new Date(x.createdAt).toLocaleString("tr-TR")}</time></div>)}</div></section></>}
 </main>}
